using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2008 Byron Wall.")]
[assembly: AssemblyCompanyAttribute("Byron Wall")]
[assembly: AssemblyProductAttribute("LastFM Client")]

